services:
  mysql:
    image: mysql:8.4
    container_name: WebCraft-MySql-JeongWonWoo
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: WebCraft
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    container_name: WebCraft-redis-JeongWonwoo
    ports:
      - "127.0.0.1:6379:6379"